# Generated by Django 4.2.26 on 2025-11-15 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100, unique=True, verbose_name='اسم المرفق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرافق',
                'db_table': 'amenity',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم العقار')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='السعودية', max_length=100, verbose_name='البلد')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('under_maintenance', 'تحت الصيانة')], default='active', max_length=20, verbose_name='حالة العقار')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='الحد الأقصى للإقامة')),
                ('default_daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر اليومي الافتراضي')),
                ('check_in_time', models.TimeField(default='15:00:00', verbose_name='وقت تسجيل الدخول')),
                ('check_out_time', models.TimeField(default='11:00:00', verbose_name='وقت تسجيل الخروج')),
                ('is_child_friendly', models.BooleanField(default=False, verbose_name='مناسب للأطفال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.propertyowner', verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع عقار',
                'verbose_name_plural': 'أنواع العقارات',
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(verbose_name='رابط الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_main_image', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
                'db_table': 'property_image',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.propertytype', verbose_name='نوع العقار'),
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included_in_price', models.BooleanField(default=True, verbose_name='مشمول في السعر')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity', verbose_name='المرفق')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مرفق عقار',
                'verbose_name_plural': 'مرافق العقارات',
                'db_table': 'property_amenity',
                'unique_together': {('property', 'amenity')},
            },
        ),
    ]
