# Generated by Django 4.2.26 on 2025-11-15 17:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offers_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز العرض')),
                ('description', models.TextField(verbose_name='وصف العرض')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_amount', 'مبلغ ثابت')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الخصم')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار (اختياري)')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأصلي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ الخصم')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('status', models.CharField(choices=[('pending_owner_approval', 'في انتظار موافقة المالك'), ('confirmed', 'مؤكد'), ('rejected_by_owner', 'مرفوض من المالك'), ('cancelled_by_user', 'ملغي من المستخدم'), ('cancelled_by_owner', 'ملغي من المالك'), ('completed', 'مكتمل')], default='pending_owner_approval', max_length=30, verbose_name='حالة الحجز')),
                ('payment_status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('partially_paid', 'مدفوع جزئياً'), ('refunded', 'مسترد'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('owner_response', models.DateTimeField(blank=True, null=True, verbose_name='استجابة المالك')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.offers', verbose_name='العرض المطبق')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='العقار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('blocked_by_owner', models.BooleanField(default=False, verbose_name='محجوز بواسطة المالك')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر خاص')),
                ('is_tentative', models.BooleanField(default=False, verbose_name='حجز مؤقت')),
                ('hold_expiry', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الحجز المؤقت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('blocked_by_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking', verbose_name='محجوز بواسطة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'توفر',
                'verbose_name_plural': 'التوفر',
                'db_table': 'availability',
                'unique_together': {('property', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BookingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.availability', verbose_name='التوفر')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='الحجز')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'يوم حجز',
                'verbose_name_plural': 'أيام الحجوزات',
                'db_table': 'booking_day',
                'unique_together': {('booking', 'date')},
            },
        ),
    ]
